[build]
  command = "npm run build"
  publish = "dist/public"

[build.environment]
  # Supabase გარემოს ცვლადები
  VITE_SUPABASE_URL = "https://useqcwqtitdtdxuutzxv.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVzZXFjd3F0aXRkdGR4dXV0enh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MjA0MjUsImV4cCI6MjA2MDI5NjQyNX0.z6NKksFYjokWV9DafsZDUN8-F1gkyZ6eCvmvbO3CnhE"

# API პროქსი - გადაამისამართებს /api/* მოთხოვნებს ბექენდზე
[[redirects]]
  from = "/api/*"
  to = "https://universal-toolkit-server.onrender.com/api/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

# SPA რედირექტი
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200