[build]
  command = "npm run build"
  publish = "dist/public"

[build.environment]
  # Supabase გარემოს ცვლადები
  VITE_SUPABASE_URL = "https://[your-project-id].supabase.co"
  VITE_SUPABASE_ANON_KEY = "your-anon-key"

# API პროქსი - გადაამისამართებს /api/* მოთხოვნებს ბექენდზე
[[redirects]]
  from = "/api/*"
  to = "https://universal-toolkit-server.onrender.com/api/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

# SPA რედირექტი
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200